"use client";

// ============================================================
//  장표 아이콘 — 내용(JSON)이 이름으로 부르는 아이콘 목록
// ------------------------------------------------------------
//  내용은 저장소 밖에 있어 아이콘을 이름 글자로만 고른다. 여기 없는 이름은
//  빈 칸이 된다 (upload-deck 이 모르는 이름을 잡는다).
// ============================================================

import {
  AlertTriangle,
  ArrowRight,
  Ban,
  Bot,
  Briefcase,
  Building2,
  Calculator,
  CalendarDays,
  CheckCircle2,
  CircleHelp,
  CircleX,
  ClipboardCheck,
  Clock,
  Coins,
  Crown,
  Eye,
  FileText,
  Flame,
  Gauge,
  Gavel,
  GraduationCap,
  Handshake,
  Heart,
  Hourglass,
  Landmark,
  Layers,
  LineChart,
  ListChecks,
  Lock,
  MapPin,
  Megaphone,
  Network,
  Package,
  Percent,
  PiggyBank,
  Repeat,
  Rocket,
  Scale,
  School,
  Send,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Split,
  Store,
  Target,
  TrendingUp,
  Trophy,
  User,
  UserCheck,
  UserMinus,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { DeckIconName } from "@/lib/neander/decks/icon-names";

/** 이름 목록(icon-names.ts)과 빠짐없이 맞아야 한다 — 타입이 확인한다 */
export const ICONS: Record<DeckIconName, LucideIcon> = {
  alert: AlertTriangle,
  arrow: ArrowRight,
  ban: Ban,
  bot: Bot,
  briefcase: Briefcase,
  building: Building2,
  calculator: Calculator,
  calendar: CalendarDays,
  check: CheckCircle2,
  question: CircleHelp,
  x: CircleX,
  clipboard: ClipboardCheck,
  clock: Clock,
  coins: Coins,
  crown: Crown,
  eye: Eye,
  file: FileText,
  flame: Flame,
  gauge: Gauge,
  law: Gavel,
  education: GraduationCap,
  handshake: Handshake,
  heart: Heart,
  hourglass: Hourglass,
  bank: Landmark,
  layers: Layers,
  chart: LineChart,
  list: ListChecks,
  lock: Lock,
  pin: MapPin,
  megaphone: Megaphone,
  network: Network,
  package: Package,
  percent: Percent,
  piggy: PiggyBank,
  repeat: Repeat,
  rocket: Rocket,
  scale: Scale,
  school: School,
  send: Send,
  shieldAlert: ShieldAlert,
  shield: ShieldCheck,
  sparkles: Sparkles,
  split: Split,
  store: Store,
  target: Target,
  trend: TrendingUp,
  trophy: Trophy,
  user: User,
  userCheck: UserCheck,
  userMinus: UserMinus,
  users: Users,
  wallet: Wallet,
  zap: Zap,
};

export function Icon({ name, size = 28 }: { name?: string; size?: number }) {
  const C = name ? (ICONS as Record<string, LucideIcon>)[name] : undefined;
  return C ? <C size={size} strokeWidth={2} aria-hidden /> : null;
}
